server:
  port: 18081

spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms
    username: rootlocalhost
    password: root
  redis:
    host: localhost

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.xxx

